[Feature] Add join, default image #6
Devocean-TechWave/OLOL-backend pull request #10
Opened 2024-07-30 05:18 UTC by jungddddd

## ✅ 풀\_리퀘스트 체크리스트

- ✅  PR 제목: [Feature/Fix/Refactor...] 작업 내용 한 줄 요약 (브랜치 이름) #이슈번호
- ✅ commit message 가 적절한지 확인해주세요.
- ✅ 적절한 branch 로 요청했는지 확인해주세요.
- ✅ Assignees, Label 을 붙여주세요.
- ✅ 주의 사항과 관련해 꼭 확인해야 할 사람이 있다면 Reviewer 로 등록해주세요.
- ✅ PR이 승인된 경우 해당 브랜치는 삭제해 주세요!

<br/>

## 🔄 변경 사항

소셜로그인 후 추가정보기입 (회원가입)
image controller, service 추가 
- 프로필 기본이미지 olol 캐릭터로 설정

<br/>

closes: #6

<br/>

2024-07-31 02:46 UTC, Hawardshin requested changes
코드에서 변경할만한 부분들 코멘트 남겨뒀습니다.
리뷰가 좀 늦은점 죄송합니다. 수정해주시면 빠르게 확인하도록 하겠습니다.
커밋이 쌓여서 아래쪽에 있는 다른 풀리퀘는 다 close 해주시고 이거 하나로 하면 될듯합니다!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/dto/reponse/ResponseDto.java
> +}
이거 이름 ResponseDto인거 헷갈릴 것 같은데 조금 더 구분하기 쉽게 바꿔줄 수 있을까요? 글로벌로 쓸 것 같으면 글로벌로 만드셔도 될 것 같아요!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/exception/ApiException.java
> +public class ApiException extends RuntimeException {
이것도 이름이 ApiException이라서 만약 이대로 쓰고 싶으면 global package 하나 빼서 거기에 exception 넣는게 좋아보입니당!
아니면 이름을 바꾸는게 좋아보여요!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/exception/ApiExceptionHandler.java
> +public class ApiExceptionHandler {
이것도 글로벌로 하거나 login에만 한정지어서 이름을 바꾸거나 하면 좋을 듯 합니다!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/service/LoginService.java
> +	private final WebClient webClient2 = WebClient.builder().baseUrl("https://kapi.kakao.com").build();
이거 이름 1,2 말고 조금 명시적으로 바꾸면 좋을 것 같아요!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/service/LoginService.java
> +	private String redirectUri;
이것도 ConfigurationProperties 쓰고 KakaoProperties 로 분리해서 사용하는게 어떨까요?

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtProvider.java
> +
밑에 ConfigurationProperties 사용했던데 여기도 통일되게 사용하면 어떨까요? JwtProperties 클래스를 빼고 그걸 주입받아서 쓰는게 더 좋은 패턴 같아 보여서 말씀 드려요!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/repository/UserRepository.java
> +}
Optional 을 사용하는게 NPE를 방지하기 좋을 것 같아보여요!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/controller/MyPageController.java
> +	public ResponseEntity<ResponseDto> getMyInfo(Authentication authentication) {
이거 다 ResponseDto를 쓰는 패턴보다는 명시적으로 어떤 Dto 반환하는지 정해주는게 더 좋아보여요! 
컨트롤러를 봤을 때 내부를 봐야 어떤걸 반환하는지 알 수가 있어서 그렇게 생각합니다.
다른 컨트롤러 코드들도 그렇게 바꾸는게 어떨까요?

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/controller/JoinController.java
> +public class JoinController {
join controller와 지금 login controoler로 따로 빼셨는데 user controller 로 합치고 거기서 join과 login으로 나누는게 더 좋아보입니다!

2024-07-31 02:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/controller/ImagesController.java
> +public class ImagesController {
이것도 이미지 컨트롤러로 빼는것보다 
/users/images
로 해서 user 컨트롤러에 연결하는게 나아보입니다! 합쳐주시면 감사할 것 같고 노션에도 반영부탁드려요!

2024-08-02 09:33 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/model/UserPrincipal.java
> +public class UserPrincipal implements UserDetails {
이 파일은 Auth 쪽에 있는게 낫지 않을까요?

2024-08-02 09:34 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/model/User.java
> +	@Column(name = "snsid", unique = true)
sns_id 가 더 좋아보여요!

2024-08-02 11:59 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/constant/GrantType.java
> +	private String name;
이거 final 붙혀주면 좋을듯!
https://yeti.tistory.com/286

2024-08-04 10:25 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/auth/JwtProvider.java
> +
Kakaoproperties 분리해서 진행하는건 아무문제 없었는데 JwtProperties는 따로 분리해서 만들면 계속 오류나... 이게 jpa 내에서는 오류 없는데 서버로 카카오로그인 진행하면 리다이렉트안되고 403오류 떠... 디버깅 해보니 accesstoken이랑 refreshtoken이 null 반환한다고 하는데 뭐가 문제지...  jwt발급부분이라 로직 수정하면 반환이 안될 수도 있는건가..?

2024-08-04 10:29 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtProvider.java
> +
이것만 봐서는 모르겠는데 음 properties들 잘 받아와지나요?
Print로 한번 제대로 들어가는지 찍어보는 것도 좋을듯!

2024-08-04 10:30 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/auth/JwtProvider.java
> +
이거랑 같이 저번에 리뷰 달아줬던 whitelist 부분 따로 application.properties로 빼고 SecurityProperties 만들어서 따로 관리하는 부분도 디버깅해보니까 여기도 문제라고 오류뜬다... 저번에 수정해서 올렸을때 그냥 jpa에서 오류 없길래 서버 로그인 연결까지 다시 안해봤거든 ㅜㅜ 지금 보니까 이것도 403뜨는데 계속 수정해봐도 왜 오류나는지 이해할 수 없따......-_-

2024-08-04 10:33 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtProvider.java
> +
오류가 뭐라고 나는지를 알아야할 것 같은데
아마 제대로 값을 못 받아오는 문제 아닐까..?

2024-08-05 04:35 UTC, merged