feat: OAuthLogin #1
Devocean-TechWave/OLOL-backend pull request #3
Opened 2024-07-27 18:46 UTC by jungddddd

## 🔄 변경 사항

카카오 로그인 구현완료

<br/>

closes: #1 

## 👨🏻‍💻 테스트 체크리스트

- 카카오 로그인 테스트 

<br/>

2024-07-28 07:46 UTC, Hawardshin requested changes
고생 많으셨습니다. 구현이 상당히 빨랐네요!
작업량이 많으셔서 모든 코드를 자세히 보지는 못했지만, 몇몇 보이는 수정할만한 부분들 코멘트로 남겨뒀으니 확인해주시면 감사하겠습니다.
그리고 Commit 전에 CheckStyle 체크 부탁드립니다. 현재 CheckStyle에 안 맞는 코드가 많이 보이네요. 수정해주시면 감사하겠습니다!

참고: 풀리퀘스트 취소할 필요 없이 수정 요청드린 사항들 하나씩 커밋해서 푸쉬하시면 현재 pull request에 반영 됩니다.

2024-07-28 07:46 UTC, Hawardshin commented on src/main/resources/application.properties
> +springdoc.swagger-ui.path=/swagger-ui
이거 아에 파일 자체를 제거하는게 좋을 것 같아요! 기록이 남아있어서 시크릿키를 볼수 있어요!
https://cobi-98.tistory.com/48 이 링크 참고해서 해주면 될 것 같습니다.

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/exception/Error.java
> +    ;
이거 코드가 무슨 코드에요?

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/config/SecurityConfig.java
> +	};
이거 설정파일로 빼는게 좋아보입니다!

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +		} catch (io.jsonwebtoken.security.SecurityException | MalformedJwtException e) {
이거 Import 보기 좋게 부탁드려요

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +	public Claims validateByExpiredToken(String token) {
validateByExpiredToken이랑 validateToken 이랑 코드가 제가 보기에는 거의 같아보이는데, allowExpired를 추가해서 validateToken에 인자로 넣으면 더 보기 좋을듯 합니다.

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/model/RefreshToken.java
> +@Setter
엔티티는 세터 롬북 말고 꼭 필요한것만 세터 만들어주세요

2024-07-28 07:46 UTC, Hawardshin commented on build.gradle
지금 이 파일에서 컴플릭 나서 머지가 안돼요! resolve 해주세요

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/model/User.java
엔티티 erd에 맞춰서 @Column으로 이름 지정 부탁드려요!
추가적으로 erd에서 추가된 부분들이 있어보이는데 필요한 부분이라면 erd에 반영 부탁드립니다.

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/constant/UserStatus.java
> +}
이건 enum으로 두는 것보다 isdelete boolean 값으로 하나만 두는게 나아보입니다.

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/dto/UserDto.java
> +	private LocalDateTime updatedTime;
create_at, update_at는 baseEntity로 빼서 상속해서 진행해도 될듯합니다.
참고할만한 글 첨부할께요
https://oh-sh-2134.tistory.com/108

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/model/User.java
지금 이름이 카멜케이스로 되어있는데 명시적으로 바꿔주세요! 
예시 : @Column(name=profile_url)

2024-07-28 07:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/user/service/ImagesService.java
> +			throw new ApiException(Error.NOT_EXIST_IMAGE);
Exception Catch 이후 사용자에게 다시 throw 하는 패턴이 더 좋지 않을까 싶어요!

2024-07-28 10:37 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/controller/LoginController.java
> +	@Operation(summary = "카카오 로그인",
이쪽도 import 맞춰주세요!

2024-07-28 10:46 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +public class JwtUtil implements InitializingBean {
Util Class Provider에서 다 처리할 수 있을 것 같은데 따로 뺀 이유가 있을까요?

2024-07-29 08:01 UTC, closed without merging

2024-07-29 08:11 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/exception/Error.java
> +    ;
로그인 관련 예외처리를 열거형으로 정리한거에요! 혹시 따로 필요하지 않은 부분일까용..??

2024-07-29 09:20 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +		} catch (io.jsonwebtoken.security.SecurityException | MalformedJwtException e) {
혹시 이게 무슨뜻이야? parserBuilder 메서드 사용해서 구현해달라는 뜻이얌...??

2024-07-29 09:32 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +		} catch (io.jsonwebtoken.security.SecurityException | MalformedJwtException e) {
아아 io.jsonwebtoken.security.SecurityException 이 부분 말한겁니다!!

2024-07-29 09:41 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +		} catch (io.jsonwebtoken.security.SecurityException | MalformedJwtException e) {
아아 넹넹 이해했습니당 수정해서 push할께용

2024-07-29 09:48 UTC, devyubin commented on src/main/java/com/techwave/olol/login/exception/Error.java
> +    ;
예외 처리는 추후 global handler로 처리하는 것 어떨까요?

2024-07-29 11:36 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/auth/JwtUtil.java
> +public class JwtUtil implements InitializingBean {
음..  JWT 토큰 생성, 검증, 파싱 같은 기본작업이랑 비즈니스로직 처리하는거랑 클래스 나눠서 구현하는게 나중에 혹시라도 수정사항 생기면 수정하기 좋대...! 사실 그냥 나누는게 좋다는 글을 봐서 나눠서 구현했어 하하

2024-07-29 13:12 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/controller/LoginController.java
> +	@Operation(summary = "카카오 로그인",
요기 @io.swagger.v3.oas.annotations.responses.ApiResponse 이 부분 import하고 @ApiResponse 수정하면 계속 다른 파일들에 오류가 뜨는데 뭐가 문제인지 모르겠옹...  이거랑 com.techwave.olol.login.dto.reponse.ApiResponse랑 어노테이션 동시에 사용하면 충돌나서 같이쓰면 안된다고만 뜨는데 이해를 못함둥.....

2024-07-29 13:18 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/exception/Error.java
> +    ;
그럼 이거는 그냥 빼고 풀리퀘 올릴까?

2024-07-29 13:37 UTC, Hawardshin commented on src/main/java/com/techwave/olol/login/controller/LoginController.java
> +	@Operation(summary = "카카오 로그인",
이름이 같았구나..! Dto이름이 로그인에서 사용하는건데 ApiResponse인건 혼란을 줄 수 있을 것 같아! 
이름을 로그인에 한정하는 dto로 명시적으로 바꿔주고 swagger의 ApiResponse는 짧게import 할 수 있도록 하면 좋지 않을까 싶습니당~~

2024-07-29 13:50 UTC, devyubin commented on src/main/java/com/techwave/olol/login/exception/Error.java
> +    ;
현재 사용하고 있는 코드 아닌가요? 사용중이라면 일단 현재 코드 올린 후 추후 exception을 리팩토링 하는 것이 나을 것 같아요

2024-07-29 14:00 UTC, jungddddd commented on src/main/java/com/techwave/olol/login/controller/LoginController.java
> +	@Operation(summary = "카카오 로그인",
와 바보다 이름이 같네... 그래서 뜨는 오류구나.... 감사합니당 ㅠ^ㅠ 덕분에 수정완료했어용